#!/bin/bash

git clone lvl1-kdilax5o@stripe-ctf.com:current-round current-round-mirror
cd current-round-mirror
git fetch --all > /dev/null
git reset --hard origin/master > /dev/null
lastsha=$(git rev-parse HEAD)
PAGER=

while :; do
	git fetch --all > /dev/null
	git reset --hard origin/master > /dev/null
	sha=$(git rev-parse HEAD)
	user=$(git log -1 --pretty=%cn | xargs echo -n)
	if [ "$sha" != "$lastsha" ] && [ "$user" != "pushrax" ]; then
		echo "RESTARTING -- $lastsha -> $sha -- $user"
		lastsha="$sha"
		killall gitminer
	fi
	sleep 10
done
